# Generated by Django 2.1.7 on 2019-03-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Profile Bio', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Profile Description', max_length=200),
        ),
    ]
