# Generated by Django 2.1.7 on 2019-03-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190331_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='users',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
