# Generated by Django 2.2 on 2019-05-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20190502_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
