# Generated by Django 2.2 on 2019-05-04 01:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tags',
        ),
        migrations.AddField(
            model_name='room',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GS', 'General Software'), ('CC', 'Code Challenges'), ('D', 'Design (UI/UX)'), ('WD', 'Web Dev'), ('MD', 'Mobile Dev'), ('GD', 'Game Dev'), ('IT', 'Tech & IT'), ('AR', 'Art'), ('C', 'Casual'), ('AC', 'Academic'), ('O', 'Other')], default='O', max_length=29),
        ),
    ]
