# Generated by Django 2.2 on 2019-05-04 02:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20190504_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('GS', 'General Software'), ('CC', 'Code Challenges'), ('D', 'Design (UI/UX)'), ('WD', 'Web Dev'), ('MD', 'Mobile Dev'), ('GD', 'Game Dev'), ('IT', 'Tech & IT'), ('AR', 'Art'), ('C', 'Casual'), ('AC', 'Academic'), ('O', 'Other')], default=['O'], max_length=29),
        ),
    ]
