# Generated by Django 2.1.7 on 2019-03-21 02:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190319_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contributors',
            field=models.ManyToManyField(null=True, related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='project_image',
            field=models.ImageField(default='default_project_image.png', upload_to='project_pics'),
        ),
    ]
