# Generated by Django 2.1.7 on 2019-03-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190321_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='post',
            name='git_link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TR', 'Travel'), ('FO', 'Food'), ('SC', 'School'), ('CA', 'Career'), ('EV', 'Events'), ('EN', 'Entertainment'), ('AR', 'Art'), ('TE', 'Tech'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
