# Generated by Django 2.1.7 on 2019-03-23 01:04

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190323_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('TR', 'Travel'), ('FO', 'Food'), ('SC', 'School'), ('CA', 'Career'), ('EV', 'Events'), ('EN', 'Entertainment'), ('AR', 'Art'), ('TE', 'Tech'), ('OT', 'Other')], default='OT', max_length=26),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
