# Generated by Django 2.1.7 on 2019-03-24 03:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190323_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DE', 'Design (UI/UX)'), ('CC', 'Code Challenges'), ('DB', 'Database'), ('TT', 'Software Testing'), ('WE', 'Web Dev'), ('MB', 'Mobile Dev'), ('GD', 'Game Dev'), ('IT', 'Tech & IT'), ('AR', 'Art'), ('EN', 'Enteratinment'), ('GA', 'Gaming'), ('BU', 'Business'), ('AC', 'Academic'), ('LY', 'Lifestyle')], max_length=41),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
