# Generated by Django 2.1.7 on 2019-03-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190324_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(default='Summarize me!', max_length=300),
        ),
    ]
