# Generated by Django 2.2 on 2019-05-04 18:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
