# Generated by Django 2.2 on 2019-05-05 02:02

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Profile Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Profile Bio', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=versatileimagefield.fields.VersatileImageField(default='default.png', upload_to='profile_pic_hashed'),
        ),
    ]
