# Generated by Django 2.2 on 2019-05-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190508_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Profile Bio', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(default='', max_length=200),
        ),
    ]
