# Generated by Django 2.2.1 on 2019-05-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190508_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hire',
            field=models.BooleanField(default=True),
        ),
    ]
